### PR TITLE
Feature/strategy

### PR DESCRIPTION
**Pull request by timothygalvin**
new view for BACNet and OPC-UA Machinery schemas to support NPL Stage 2 onboarding:

image

### CODE REVIEW

**Comment by mchru** [comment]
@timothygalvin will do
@moulhamPy please see to this

**Review by moulhamPy — CHANGES_REQUESTED** [review]
The model is not complete. Please include machinary.job library that we need for process domain.

**Comment by timothygalvin** [comment]
@mchru @Dr-Eti 
guys, here is the updated model

image

**Review by timothygalvin — COMMENTED** [review]
changes made!

**Comment by timothygalvin** [comment]
@Dr-Eti 
Hi Ettore,

i've updated the layered view for objective 9.  no major changes, just updated a few descriptions.  the model itself doesnt change:

here is the old baseline (02.02.02):
https://mmic-collaboration.github.io/?view=id-3d72a408a05b4b6995df4ccea417840d

Here is what the new model looks like:
image

**Comment by Dr-Eti** [comment]
@timothygalvin thanks for the update - at quick glance: I have some doubts on the path leading form (advanced) "analytics" - a generic business service - to inventory "optimization" capabilities passing through (data?) "visualisation and dashboard" capabilities: if anything because visualisation per se does not mean optimisation - in fact, it does not seem to imply computations being carried out on the underpinning data. Unless there is one already, I wonder if it's worth developing a full example re how "typical" decision parameters linked to so-called optimal inventory replenishment policies (skipping the caveats for the moment) for the sake of clarity? More than happy to do it, just not sure in which format is appropriate for this thread...

**Pull request merged**
