### PR TITLE
Feature/technology

### PR DESCRIPTION
**Pull request by sp8ndey**
Please review and approve the changes

### CODE REVIEW

**Comment by timothygalvin** [comment]
@sp8ndey 
Hi Surya, 

General comment... Please included details of the objects/views you have changed in your checkin comments.  makes its easier to identify the material for review.

This is a review of "Technology View- AWS Sensor Event Processing" view

and

"Application View - Sensor Events Component Model End-to-end - Technology Mapping"

1. Main thing is that the end-to-end flow requires two instances of the Domain Gateway to fulfil the RT release story, so events can be seen flowing from PLANT into PROCESS domains.  This is needed to show the end-to-end flow.  We discussed and said we could do this in the application layer, but i don't mind where we put this as long as its there.  This is the most important comment.
2.The industrial connector doesnt appear in ""Application View - Sensor Events Component Model End-to-end - Technology Mapping".  does this replace the Sensor Event Broker?  we need to complete the mapping picture.
3. Following on from point 2. above, where is the transformation ?  the original purpose of "PROCESS Domain Broker" was just a 'pass-through', but in your model we are now doing transformation?
4. where do we do orchestration?
5. same question for enrichment... e.g. adding the machine id to the sensor event?
6. Can we clarify what is "Process Server" and "Process Functions"?  indeed, what is the "Process" node?
7. Suggest we create an abstraction of "PLANT Domain Schema" to "Domain Schema".  We can then use this to realise the "Domain Interface".

**Comment by sp8ndey** [comment]
SP and Tim together has reviewed and updated aligned the technology view and application view. @timothygalvin , are ok to approve and merge the with development branch.

**Comment by timothygalvin** [comment]
@sp8ndey @jess-andrews @martin-keane-cpi @jess-andrews 

Surya, we are aligned!  PROCESS Domain components specialises the Domain Gateway.  The Application / Tech mapping is in  "Application View - Sensor Events Component Model End-to-end - Technology Mapping"

thanks, good to go

Here are the final pictures:

image
image

**Review by timothygalvin — APPROVED** [review]
good to go, see final comment

**Pull request merged**
