### PR TITLE
Feature/strategy

### PR DESCRIPTION
**Pull request by timothygalvin**
@martin-keane-cpi 
Hi Martin, have updated PROCESS CDM with some ISA95 aligned content.  Also, have added a traceability view.  See:
 - Business Data View - PROCESS Domain CDM - Level 1
 - Business Data View - Domain Traceability

### CODE REVIEW

**Comment by jess-andrews** [comment]
@timothygalvin 
Just had a quick look at the model. Couple of initial points:
1. We now have two views with the same name "Business data view - PROCESS Doman CDM - Level 1". They have different version numbers so maybe we should put that in the name to differentiate?
2. The only thing that seems to be missing from Martin's miro board is the batch report. That isn't directly related to ISA95, so possibly outside the scope of this story.

**Comment by jess-andrews** [comment]
@timothygalvin Martin found an OPC UA standard regarding lab objects/interfaces: https://reference.opcfoundation.org/LADS/v100/docs/#7. Might be helpful for your LIMS related efforts.

**Comment by martin-keane-cpi** [comment]
Hi Tim, 

Couple of things: 

- we discussed putting job order and job response into a container called job which then links to "product batch" and "production run"

- we thought production run was the wrong name as it could confuse people as production run could describe all the work done during a day / week etc. The term should instead clearly highlight that this is the indivisible atomic unit of production so on PACE this would be single bottle made, this would be part of a job and multiple of these could be grouped together into a batch. (we suggested something like process unit but I don't like that term) maybe "work unit" or "job unit" or "unit of work"

- I think I would rename machine as work centre as these are what process jobs. machines are within work centres . This would suggest that it isn't the machines themselves which return job responses. there must be an intermediary e.g. SCADA although likely also possible that one machine could be a work centre. 

- Reading ISA 95 again it states job orders have procedures or workflows which they follow. They use the term "work master" to refer to both of these. I think this would replace recipe / machine configuration / machine setting ...... which should all be in the PLANT domain. ISA 95 specifies that a work master includes an ISA88 master recipe or ISA 95 workflow procedure

 (NOT TO DO WITH ISA95)
- I also think the fundamental structure may be wrong as one type of process event is the job response so it needs to have a relationship with plant domain. I think it would be better to have two things come from PLANT domain - job response and PLANT events the second then needs a deviation assessment to decide its batch impact. the firt it is clear which batch it refers to 

Martin

**Comment by timothygalvin** [comment]
@martin-keane-cpi 

PROCESS CDM checked in, now at 0.5.1.  This is what we agreed i think:

1. Work Master is the template for Job.  we can lose Work Master Instance
2. The magic "Intermediate Process" object which joins Job to equipment/batch/deviation is actually a "Unit Process", a sub part of Job.  This fits the model, but unfortunately its an ISA88 term.
3. We will look to fold in the Job Master / Recipe portion of the model into the ISA95 namespace next sprint
4. We have pushed all of the the equipment/node related stuff towards the PLANT model.  this may move out, but not in this sprint
5. The Process Control elements will also change but we will leave them where they are for now until we look at operations and control (future feature)

Note that I have added a few TBDs on the model in 0.5.1.  we can address these next sprint to create a clean baseline for the march release, but obviously still a lot of changes to make going forward.

btw, this version also contains the Lab extension changes after discussing with alec@thermofisher, as per:
https://team-cpi.monday.com/boards/4183821556/pulses/5874477139

this story, standards, is here btw:
https://team-cpi.monday.com/boards/4183821556/pulses/5985956698

**Comment by jess-andrews** [comment]
@timothygalvin @sp8ndey @martin-keane-cpi 
I've completed updates to the RT release layered view based on ThermoFisher feedback:
Layered View - 1  Real-time Release 23FEB2024

**Pull request merged**
