### PR TITLE
US146: Final draft of RT release motivation view

### PR DESCRIPTION
**Pull request by jess-andrews**
Updates to the RT release layered view and DPMM v2.0 capability map post meeting with Rob
Some questions for discussion as notes in the view

Layered View - 1  Real-time Release 28FEB2024v2

### CODE REVIEW

**Comment by rob-a-innes** [comment]
Personally I like the inclusion of personae in this view as it confirms who we're designing for. Of course, a separate view that links an individual persona to a set of capabilities / services would also have utility. I think the diagram looks really good and is a big improvement on October version.

**Comment by timothygalvin** [comment]
i agree with @rob-a-innes

**Comment by sbolder77** [comment]
As per meeting with Alec and I:
On review with Simon: in the yellow band, does one of the services include SOP and work instructions. (Is it the Recipe Management Service?)
On blue band: Should Quality Management Service feed Maintenance and Calibration?
Do we need to include a Warehouse Management System (WMS) alongside ERP ?

**Comment by jess-andrews** [comment]
@sbolder77 @rob-a-innes @timothygalvin 
Thanks for the review. Updated the view accordingly. The only bit I wasn't sure on was which service would realise the 'work order management' capability. I put recipe management service per Alec/Simon's suggestion, but I wonder if it's more like a planning/scheduling service? We don't currently have in that in the model but could add it. 

New view below, including some changes to the motivation elements to address earlier feedback about the hierarchy of goal/outcome. 

Let's try and close this out on Monday if possible. @rob-a-innes - do you fancy learning how to approve these requests (I'll show you, it's easy)?!

Layered View - 1  Real-time Release1MAR2024

**Comment by sbolder77** [comment]
@jess-andrews the update is looking good. I don't think we recommended a work order management service. Do you mean work instruction? The work instruction is similar to an SOP so it is more like a method that someone will execute that ties into training and validation. Feel free to ping me if you need some clarification.

**Comment by rob-a-innes** [comment]
Work order / work instruction commonly organised via MES.
@jess-andrews happy to have training!

**Comment by jess-andrews** [comment]
@sbolder77 - messaged you on Teams. Not sure if that'll come through due to security settings so copied below:

I thought work orders and work instructions were the same thing! I can't see a capability in our map that explicitly calls out work instructions. Can you see anything relevant in the map below? We can add one if not
 
Strategy View - (BioPhorum DPMM 2 0) Capabilty Map Level 0

**Review by rob-a-innes — APPROVED** [review]
Following review with JA, submitting my approval

**Pull request merged**
