### PR TITLE
Various changes in the motivation layers

### PR DESCRIPTION
**Pull request by timothygalvin**
Prep for F2F:

 - new layered view for 10. Dynamic scheduling
 - updated stakeholder view
 - updated business drivers
 - tidied up motivation elements

image

image

image

image

### CODE REVIEW

**Comment by jess-andrews** [comment]
@timothygalvin - piggybacking on your pull request with some updates to the business views to align with design spec

**Comment by timothygalvin** [comment]
@jess-andrews 


changes look good.  if you are content, please approve and merge (I cannot because the PR belongs to me).

**Review by jess-andrews — APPROVED** [review]
Looks great Tim. In the next version, let's add the distinction between local/global community to the stakeholders view. Not urgent though.

**Comment by rob-a-innes** [comment]
'Demand signal' gets pretty low billing considering the likely importance in dynamic scheduling. Maybe we could focus on that a little more in a subsequent version?

**Pull request merged**
