### PR TITLE
re-introduced application - technology mapping for E2E sensors

### PR DESCRIPTION
**Pull request by timothygalvin**
This PR is primarily to include the data objects into the motivation view ([US186](https://team-cpi.monday.com/boards/4183821556/pulses/6137725520)), but also including some cleanup tasks from the merge resolution at the end of last sprint

### CODE REVIEW

**Comment by timothygalvin** [comment]
@jess-andrews @rob-a-innes 

Have added the data products to the view. If you are happy, go ahead and merge... or not! if you have edits :) 

here's the pic:
objective-1-with-data-products

**Comment by rob-a-innes** [comment]
One small thought - Personnel Qualifications - this would come from the PEOPLE domain, I presume, and we'd need their rota/schedule as well. So you have personnel resource available on shift, with the right qualifications. Maybe heading into unnecessary detail :) ...

**Comment by timothygalvin** [comment]
> @rob-a-innes @timothygalvin There's another view mapping data products to domains, which captures your comment about PEOPLE domain. Business Data View - RT Release Business Data Products
> 
> Would the rota be checked during the release process? I think we'd need correctly qualified people to be physically running the lines, which probably translates to a planning/scheduling capability we need to add to the map. But I'm not sure we need the rota itself as a data product for release? I've just agreed with Tim to do a separate pull request for the larger changes to the model we discussed yesterday. I'll include this change there.
> 
> My only build on the data products would be around 'goods in'. Is it actually the CoA we need? Maybe the batch record should be on there as well?

Yes, i did this view last night.  I didnt want to share it because its not tidy, but you can see the relationships

**Comment by jess-andrews** [comment]
@timothygalvin  
> My understanding is that the QP Dashboard replaces the "Batch Record" we have today. We have a concept of a "Batch", but it is the Deviation information we are most interested in when it comes to Batch.... I think.

Good point, I agree with that. Do you have any thoughts on goods in vs CoA?

**Comment by timothygalvin** [comment]
@rob-a-innes @jess-andrews 

Have updated the data product mapping view for real-time release to make it more readable.  Hopefully this clarifies the points.  This is commited 

image

**Review by jess-andrews — APPROVED** [review]
Looks great Tim, nice one

**Pull request merged**
