### PR TITLE
Feature/strategy

### PR DESCRIPTION
**Pull request by timothygalvin**
hi all,

These are changes to the PROCESS and PLANT CDMs to support the two stories in the last sprint:
https://team-cpi.monday.com/boards/4183821556/pulses/5637705641
and
  https://team-cpi.monday.com/boards/4183821556/pulses/5602268504

Summary of changes:
 - moved alarms into PLANT
 - refactored treatment of 'Deviations'
 - included domain interactions
 - added Lab sub-domain to PLANT

@martin-keane-cpi 
I think these structures will now work end-to-end for the real-time release scenario, but we need to test it with a real case now.

Thanks

### CODE REVIEW

**Comment by jess-andrews** [comment]
Hi Tim, I've reviewed these changes, comments below. Don't know if the pictures will come through... let's see! Thanks

Summary:
- moved alarms into PLANT - agree
- refactored treatment of 'Deviations' - agree, some builds below regarding lab domain
- included domain interactions - agree with all
- added Lab sub-domain to PLANT - agree, but this in in PROCESS (which I think is correct)

PLANT

For discussion: What is the relationship between equipment method and recipe? Does a recipe state that you must execute a specific equipment method? Or are they separate? Does equipment method only refer to lab equipment and recipe only refer to manufacturing equipment? Wondering if there is a relationship between these objects and the lab sub-domain that is not currently pictured.

In PLANT, we define 2 equipment contexts: QC lab and production line. In PROCESS, the production line context appears to be the main domain, and QC lab is a sub-domain. Wondering if there should be 2 sub-domains: QC lab and production line? E.g.
PLANT sub domains

PROCESS

'Deviation' needs a definition. We need to be clear on the difference between a deviation and an incident.

We talk a lot about RT release conditions - do we need to bring this concept into the model? How about:
Quality conditions
There might be a relationship between quality control condition and the product domain – maybe QC conditions are part of some kind of product specification?

Lab equipment can also trigger deviations. Am I correct in thinking that because sensor events come from both lab and production equipment, this means that a process event and therefore a deviation can come from either lab or production, so we don't need to call out a specific relationship between deviation and the lab sub-domain? 

If so, we may need to amend how we generate process events. They are currently triggered by 'process control rules', which to me sounds like a manufacturing specific thing. We could change it (e.g. a generic 'quality control rule') or add another trigger from the lab sub-domain (e.g. 'lab quality rule')? 

'Machine setting change' needs a definition.

**Comment by timothygalvin** [comment]
@jess-andrews @martin-keane-cpi 
Thanks for your comments, guys.  Have made changes to the CDM on the strategy branch which i will check in directly.

Martin, yes, we absolutely need to test this now with a real scenario.  that is in Sprint 2.

Jess, responses to your comments.

1. Lab Method needs more discussion.  I propose we baseline now at this version without it and roll these changes (if any) into the next baseline.
2. I have removed Incident.  this needs more discussion with Simon (he raised this point).  Propose we discuss with Simon ini Sprint 2 along with content from point 1 above.x
3. Production sub-domain: I try to avoid more than one extension unless necessary.  it increases complexity of your model (if this scenario do that, else do the other).  It also forces you to maintain two copies of the model.  If all constructs in the parent domain are valid in the sub-domain there is no need to 'fork', in my view.  My recommendation is that we go with something that works at a given point in time, and change it later if we need to.
4. I've changed the deviation model (mostly) in line with your suggestion. have a look below.  I think my proposal captures your requirement but in a simpler way.
5. The model will work for triggering of Deviations from Lab Equipment.  Process Event is raised, and knows which machine it came from through the Recipe (which could be in a Lab).  Note that: Deviations are not triggered by a Process Control Rule, but by the breaching of a Batch Release Condition.  There may be a relationship between Batch Release Condition and Process Control Rule (e.g. the one may be triggered by the other) but have not so far identified this.
6. Have added descriptions for (now) Batch Deviation and Machine Setting Change 

Pictures came through nicely in your comment, very helpful! 

image

**Comment by jess-andrews** [comment]
Hi Tim
Thanks for responses/explanations. Agree with them all, and really like your build on the deviation model. (I read the arrow the wrong way and confused myself with process control rules - I get it now!)
Happy to close this now, but I don't remember what button to press to approve?!

**Comment by martin-keane-cpi** [comment]
My brain isn't warmed up enough to give much meaningful comment but wanted to remind that their is a long standing model in ISA-88/95 which links the equipment / processes / procedures and may be what you are looing for: 
image

An example of the hierarchy in Equipment: 
image

And in process: 
image

Procedure, as I understand it is the software which controls the process in the equipment - why they chose to split it out I have no idea - probably because there are many procedures which relate to quirks of software which don't map directly to a physical process

**Comment by jess-andrews** [comment]
Totally forgot about this! How about we version the model as is for now, and add another story to the product backlog to align with the above? We could do it in sprint 3?

**Comment by timothygalvin** [comment]
@jess-andrews @martin-keane-cpi 

folks, i think the PROCESS Domain CDM as-is will accommodate the ISA-88/95 model as follows:
 - the "Procedural Control Model" is embodied in the process part of the Recipe
 - "Equipment" is covered by the "Machine Configuration"
 - The "Process Model" is covered by "Production Run".  (This will probably change name to "Batch Run" or "Batch Record" in the next sprint.)

Note, I have added a new "Machine" entity (see commit 71b758f above) to capture the top-line data on the piece of equipment.  Note that the breakdown  of machines into cells, units, and modules is 'inside' these high level entities.  We can delegate this detail to the LDM.

I propose we baseline now as-is and create a new story for sprint 3 to update both domains with an additional acceptance criterion to test the new models against ISA-88/95.  This will need to be refined when we make changes based on the input from Steven@GSK that we had today.

**Comment by martin-keane-cpi** [comment]
@timothygalvin Hi Tim, the procedural control definitely relates to the recipe. I would ague that equipment is purely specifiying which bit of equipment to use / has been used. the machine configuration is just the recipe as applied to the machine in terms of set points etc. Yes the process model relates to the actual processes. 

My thought in the meeting was that the recipe / machine set points etc. should be moved to the PLANT domain which more closely aligns to the ISA-88 model where there is separation between what you are producing and  the machines and the setpoints used which actually make it

**Comment by jess-andrews** [comment]
@timothygalvin @martin-keane-cpi 
Hi both, I like Martin's idea but also agree that the model works as is. Shall we baseline as is for now and push Martin's comment into Sprint 3 with Steven's review? I've also had an offer of a review in sprint 3 from Michael Chrubasik at NPL. They're standards experts so could help with ISA88 alignment in Sprint 3.

**Review by jess-andrews — APPROVED** [review]
As agreed, approving this version for sprint 2. 

To address in sprint 3:
DTG comments
ISA88 alignment (Martin's comments, with help from NPL)
My question about soft sensors

To address in sprint 4+:
Joe's scenario about rejecting out of spec material during a continuous process

**Pull request merged**
