### PR TITLE
Updated PROCESS CDM to 0.7.0 for US178, US188, and US112

### PR DESCRIPTION
**Pull request by timothygalvin**
changes to reflect review of US178:
https://team-cpi.monday.com/boards/4183821556/pulses/6125447511

### CODE REVIEW

**Review by jess-andrews — COMMENTED** [review]
@timothygalvin The definition still has two references to 'job execution step'. Should they be removed?

A Unit Process is a sub-process of a Job, occuring at a particular Station (TBD, 0.4.1), for a particular Product Batch.  It has precise start and end time-stamps.  A Process Event must occur within a single **Job execution step**.  A Deviation can optionally relate to a Single **Job Execution Step**.

**Comment by martin-keane-cpi** [comment]
Hi Tim, 

Going to capture my comments from earlier: 

Job step test specification I think is a difficult word to use. I would maybe use Job Step feedback specification OR Job Step response specification i.e. what data do I expect as feedback from this process to be assured the process completed successfully. The equivalent of the test result would be the machinery result. which would form a part of the job response. it has an equivalent when humans complete the task but isn't defined anywhere (Siemens call them eBR's in their MES) 

we have the test result for physical asset which would be its qualification test result. I think we have missed the test result from the qualification of the procedure i.e. the procedure does what we expected it to and we have a test to show that. 

Also missing explicitly from the model would be alarms which are a type of process event (I think process event may be too generic a term to link to directly as there are alarms vs machinery results which are both types of process events but they relate to deviations differently. Also the alarms may be coming from Environmental monitoring system or one of the machines so the evnt comes from potentially different sources. 

I'm not sure about batch release test specification and link to deviation - I think the base of the model may need to be looked at again after this release 

Martin

**Comment by timothygalvin** [comment]
@martin-keane-cpi 
Hi Martin, responses below.

> Hi Tim,
> 
> Going to capture my comments from earlier:
> 
> Job step test specification I think is a difficult word to use. I would maybe use Job Step feedback specification OR Job Step response specification i.e. what data do I expect as feedback from this process to be assured the process completed successfully. The equivalent of the test result would be the machinery result. which would form a part of the job response. it has an equivalent when humans complete the task but isn't defined anywhere (Siemens call them eBR's in their MES)

I agree, it must include the response, or feedback.  But you get that automatically if you extend the[ ISA95TestSpecificationType](https://reference.opcfoundation.org/ISA-95/v100/docs/7.6.4) (which we do).  I have changed the name, but this now moves away from the nomenclature of the other four test types, defined in [ISA-95](https://reference.opcfoundation.org/ISA-95/v100/docs/#7.6.4).  

> we have the test result for physical asset which would be its qualification test result. I think we have missed the test result from the qualification of the procedure i.e. the procedure does what we expected it to and we have a test to show that.

Test Result in the model is generic across all the object types, including the new "job step" object.  So, its in there, i just haven't included it in the model because it starts to get very messy.  It will be in the LDM.  Also, consider that ISA-95 doesnt go into this level of detail either, which indicates the CDM doesn't need to be this detailed.  Is this ok?

> Also missing explicitly from the model would be alarms which are a type of process event (I think process event may be too generic a term to link to directly as there are alarms vs machinery results which are both types of process events but they relate to deviations differently. Also the alarms may be coming from Environmental monitoring system or one of the machines so the event comes from potentially different sources.

Alarms are in PLANT, currently modelled as a type of Sensor Event.  The way we've modelled it it to map Sensor Event to Process Event and Alarm to Deviation.  this will work based on our current assumptions.  however, if there are differences between machine Process Events and other Process Events, i agree we will need to remodel.  Also, when we get back to PLANT in the next release, we can look again at Sensor Event/Deviation relationship.  

Can I propose we record a potential change and look at it in the next sprint?

> I'm not sure about batch release test specification and link to deviation - I think the base of the model may need to be looked at again after this release

Agreed.  I'm not happy with it either.  Problem is, ISA-95 doesnt have any link between the Test Specification object and the test itself, which seems absurd to me.

> 
> Martin

**Comment by timothygalvin** [comment]
here, @martin-keane-cpi @jess-andrews @JessRatner 

Business Data View - PROCESS Domain CDM - Level 2 - Work Master
Business Data View - PROCESS Domain CDM - Level 1

**Comment by timothygalvin** [comment]
@martin-keane-cpi @jess-andrews @JessRatner @sbolder77

Hi all, please see follow on stories for the next (post face-to-face) Sprint for PROCESS CDM.  
- US199: https://team-cpi.monday.com/boards/4183821556/pulses/6203390843
- US200: https://team-cpi.monday.com/boards/4183821556/pulses/6203403136
- US201: https://team-cpi.monday.com/boards/4183821556/pulses/6203418108

Martin, if you are content, please comment and close the PR.

**Comment by martin-keane-cpi** [comment]
happy that we have captured future stories to fix some areas which need more work

**Review by martin-keane-cpi — APPROVED** [review]
happy with changes - need to review again after initial release

**Pull request merged**
